[package]
name = "whitelist_rs"
version = "0.1.0"
authors = ["wzv5 <wzv5@msn.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.10.8"
tokio = "0.2.22"
serde = "1.0.115"
serde_json = "1.0.57"
lru_time_cache = "0.11.0"
url = "2.1.1"
actix-web = "2.0.0"
actix-rt = "1.1.1"
log = "0.4.11"
env_logger = "0.7.1"

[profile.release]
lto = true
codegen-units = 1
